-- DEPRECATED
-- This file belongs to the old public CRUD prototype and must not be used.
-- Use Supabase migrations in `supabase/migrations/` instead.
--
-- Security reason:
-- the old prototype granted broad public access and does not meet
-- current privacy/RLS requirements.
